version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build_dev:
    docker:
      # specify the version you desire here
      - image: circleci/node:11.3
    working_directory: ~/stew
    environment:
      - NODE_ENV: development
    steps:
      - checkout
       # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - run: npm test
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  deploy:
    # This is a directory where all your repo content will be placed. 
    # Name is not that important at this case.
    working_directory: ~/stew
    environment:
      - NODE_ENV: production
    # Docker environment where we gonna run our build deployment scripts 
    docker:
    - image: circleci/node:8.11

    steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-
    
    # Install npm dependencies 🙂
    - run: npm install
    - run: npm build
    # Make things faster
    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

    # !!! This installs AWS Elastic Beanstalk CLI 'awsebcli' !!!
    - run:
        name: Installing deployment dependencies
        command: |
          sudo apt update
          sudo apt install -y python-pip python-dev
          sudo pip install awsebcli
    # !!! This runs a deployment
    - run:
        name: Deploying
        command: eb deploy stew-server-env

  
workflows:
  version: 2
  build_test_deploy:
    jobs:
    - build_dev
    - deploy:
      filters:
        branches:
          only:
          - master